/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BackendRouteRouteImport } from './routes/backend/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BundlesIndexRouteImport } from './routes/bundles/index'
import { Route as BrandsIndexRouteImport } from './routes/brands/index'
import { Route as BackendIndexRouteImport } from './routes/backend/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as PagesSlugRouteImport } from './routes/pages/$slug'
import { Route as CollectionSlugRouteImport } from './routes/collection/$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as BundleSlugRouteImport } from './routes/bundle/$slug'
import { Route as BrandsHandleRouteImport } from './routes/brands/$handle'
import { Route as BackendWmsRouteImport } from './routes/backend/wms'
import { Route as BackendUsersRouteImport } from './routes/backend/users'
import { Route as BackendSubmissionsRouteImport } from './routes/backend/submissions'
import { Route as BackendSiteSettingsRouteImport } from './routes/backend/site-settings'
import { Route as BackendSettingsRouteImport } from './routes/backend/settings'
import { Route as BackendSalesRouteImport } from './routes/backend/sales'
import { Route as BackendProductsRouteImport } from './routes/backend/products'
import { Route as BackendPagesRouteImport } from './routes/backend/pages'
import { Route as BackendOrdersRouteImport } from './routes/backend/orders'
import { Route as BackendNewsletterRouteImport } from './routes/backend/newsletter'
import { Route as BackendNavLinksRouteImport } from './routes/backend/nav-links'
import { Route as BackendMediaRouteImport } from './routes/backend/media'
import { Route as BackendLoginRouteImport } from './routes/backend/login'
import { Route as BackendLifestyleCardsRouteImport } from './routes/backend/lifestyle-cards'
import { Route as BackendIntegrationsRouteImport } from './routes/backend/integrations'
import { Route as BackendHomepageSectionsRouteImport } from './routes/backend/homepage-sections'
import { Route as BackendHomepageRouteImport } from './routes/backend/homepage'
import { Route as BackendHeroSlidesRouteImport } from './routes/backend/hero-slides'
import { Route as BackendFulfilmentRouteImport } from './routes/backend/fulfilment'
import { Route as BackendFinanceRouteImport } from './routes/backend/finance'
import { Route as BackendFeatureCardsRouteImport } from './routes/backend/feature-cards'
import { Route as BackendEmailTemplatesRouteImport } from './routes/backend/email-templates'
import { Route as BackendDraftsRouteImport } from './routes/backend/drafts'
import { Route as BackendDataTransferRouteImport } from './routes/backend/data-transfer'
import { Route as BackendCutoverRouteImport } from './routes/backend/cutover'
import { Route as BackendCustomersRouteImport } from './routes/backend/customers'
import { Route as BackendContentRouteImport } from './routes/backend/content'
import { Route as BackendCompaniesRouteImport } from './routes/backend/companies'
import { Route as BackendCommunicationsRouteImport } from './routes/backend/communications'
import { Route as BackendCommerceRouteImport } from './routes/backend/commerce'
import { Route as BackendCollectionsRouteImport } from './routes/backend/collections'
import { Route as BackendCheckoutRouteImport } from './routes/backend/checkout'
import { Route as BackendCategoriesRouteImport } from './routes/backend/categories'
import { Route as BackendCatalogRouteImport } from './routes/backend/catalog'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AccountQuotesRouteImport } from './routes/account/quotes'
import { Route as AccountInvoicesRouteImport } from './routes/account/invoices'
import { Route as AccountCompanyRouteImport } from './routes/account/company'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as BackendOrdersOrderIdRouteImport } from './routes/backend/orders.$orderId'
import { Route as BackendFinanceStatementsRouteImport } from './routes/backend/finance.statements'
import { Route as BackendFinanceRefundsRouteImport } from './routes/backend/finance.refunds'
import { Route as BackendFinanceReconciliationRouteImport } from './routes/backend/finance.reconciliation'
import { Route as BackendFinanceReceivablesRouteImport } from './routes/backend/finance.receivables'
import { Route as BackendFinancePaymentsRouteImport } from './routes/backend/finance.payments'
import { Route as BackendFinanceInvoicesRouteImport } from './routes/backend/finance.invoices'
import { Route as BackendDraftsNewRouteImport } from './routes/backend/drafts.new'
import { Route as BackendDraftsDraftIdRouteImport } from './routes/backend/drafts.$draftId'
import { Route as BackendCustomersNewRouteImport } from './routes/backend/customers.new'
import { Route as BackendCustomersCustomerIdRouteImport } from './routes/backend/customers.$customerId'
import { Route as BackendCompaniesNewRouteImport } from './routes/backend/companies.new'
import { Route as BackendCompaniesCompanyIdRouteImport } from './routes/backend/companies.$companyId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'
import { Route as BackendFinancePaymentsPaymentIdRouteImport } from './routes/backend/finance.payments.$paymentId'
import { Route as BackendFinanceInvoicesInvoiceIdRouteImport } from './routes/backend/finance.invoices.$invoiceId'

const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendRouteRoute = BackendRouteRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesIndexRoute = BundlesIndexRouteImport.update({
  id: '/bundles/',
  path: '/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendIndexRoute = BackendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackendRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const BundleSlugRoute = BundleSlugRouteImport.update({
  id: '/bundle/$slug',
  path: '/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsHandleRoute = BrandsHandleRouteImport.update({
  id: '/brands/$handle',
  path: '/brands/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendWmsRoute = BackendWmsRouteImport.update({
  id: '/wms',
  path: '/wms',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendUsersRoute = BackendUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSubmissionsRoute = BackendSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSiteSettingsRoute = BackendSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSettingsRoute = BackendSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSalesRoute = BackendSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendProductsRoute = BackendProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendPagesRoute = BackendPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendOrdersRoute = BackendOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendNewsletterRoute = BackendNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendNavLinksRoute = BackendNavLinksRouteImport.update({
  id: '/nav-links',
  path: '/nav-links',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendMediaRoute = BackendMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendLoginRoute = BackendLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendLifestyleCardsRoute = BackendLifestyleCardsRouteImport.update({
  id: '/lifestyle-cards',
  path: '/lifestyle-cards',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendIntegrationsRoute = BackendIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendHomepageSectionsRoute = BackendHomepageSectionsRouteImport.update({
  id: '/homepage-sections',
  path: '/homepage-sections',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendHomepageRoute = BackendHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendHeroSlidesRoute = BackendHeroSlidesRouteImport.update({
  id: '/hero-slides',
  path: '/hero-slides',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendFulfilmentRoute = BackendFulfilmentRouteImport.update({
  id: '/fulfilment',
  path: '/fulfilment',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendFinanceRoute = BackendFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendFeatureCardsRoute = BackendFeatureCardsRouteImport.update({
  id: '/feature-cards',
  path: '/feature-cards',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendEmailTemplatesRoute = BackendEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendDraftsRoute = BackendDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendDataTransferRoute = BackendDataTransferRouteImport.update({
  id: '/data-transfer',
  path: '/data-transfer',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCutoverRoute = BackendCutoverRouteImport.update({
  id: '/cutover',
  path: '/cutover',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCustomersRoute = BackendCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendContentRoute = BackendContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCompaniesRoute = BackendCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCommunicationsRoute = BackendCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCommerceRoute = BackendCommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCollectionsRoute = BackendCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCheckoutRoute = BackendCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCategoriesRoute = BackendCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCatalogRoute = BackendCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => BackendRouteRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountQuotesRoute = AccountQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AccountRoute,
} as any)
const AccountInvoicesRoute = AccountInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCompanyRoute = AccountCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const BackendOrdersOrderIdRoute = BackendOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => BackendOrdersRoute,
} as any)
const BackendFinanceStatementsRoute =
  BackendFinanceStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => BackendFinanceRoute,
  } as any)
const BackendFinanceRefundsRoute = BackendFinanceRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => BackendFinanceRoute,
} as any)
const BackendFinanceReconciliationRoute =
  BackendFinanceReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => BackendFinanceRoute,
  } as any)
const BackendFinanceReceivablesRoute =
  BackendFinanceReceivablesRouteImport.update({
    id: '/receivables',
    path: '/receivables',
    getParentRoute: () => BackendFinanceRoute,
  } as any)
const BackendFinancePaymentsRoute = BackendFinancePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => BackendFinanceRoute,
} as any)
const BackendFinanceInvoicesRoute = BackendFinanceInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => BackendFinanceRoute,
} as any)
const BackendDraftsNewRoute = BackendDraftsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BackendDraftsRoute,
} as any)
const BackendDraftsDraftIdRoute = BackendDraftsDraftIdRouteImport.update({
  id: '/$draftId',
  path: '/$draftId',
  getParentRoute: () => BackendDraftsRoute,
} as any)
const BackendCustomersNewRoute = BackendCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BackendCustomersRoute,
} as any)
const BackendCustomersCustomerIdRoute =
  BackendCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => BackendCustomersRoute,
  } as any)
const BackendCompaniesNewRoute = BackendCompaniesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BackendCompaniesRoute,
} as any)
const BackendCompaniesCompanyIdRoute =
  BackendCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => BackendCompaniesRoute,
  } as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRoute,
} as any)
const BackendFinancePaymentsPaymentIdRoute =
  BackendFinancePaymentsPaymentIdRouteImport.update({
    id: '/$paymentId',
    path: '/$paymentId',
    getParentRoute: () => BackendFinancePaymentsRoute,
  } as any)
const BackendFinanceInvoicesInvoiceIdRoute =
  BackendFinanceInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => BackendFinanceInvoicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/backend': typeof BackendRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/search': typeof SearchRoute
  '/trade': typeof TradeRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/company': typeof AccountCompanyRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/quotes': typeof AccountQuotesRoute
  '/admin/$': typeof AdminSplatRoute
  '/backend/catalog': typeof BackendCatalogRoute
  '/backend/categories': typeof BackendCategoriesRoute
  '/backend/checkout': typeof BackendCheckoutRoute
  '/backend/collections': typeof BackendCollectionsRoute
  '/backend/commerce': typeof BackendCommerceRoute
  '/backend/communications': typeof BackendCommunicationsRoute
  '/backend/companies': typeof BackendCompaniesRouteWithChildren
  '/backend/content': typeof BackendContentRoute
  '/backend/customers': typeof BackendCustomersRouteWithChildren
  '/backend/cutover': typeof BackendCutoverRoute
  '/backend/data-transfer': typeof BackendDataTransferRoute
  '/backend/drafts': typeof BackendDraftsRouteWithChildren
  '/backend/email-templates': typeof BackendEmailTemplatesRoute
  '/backend/feature-cards': typeof BackendFeatureCardsRoute
  '/backend/finance': typeof BackendFinanceRouteWithChildren
  '/backend/fulfilment': typeof BackendFulfilmentRoute
  '/backend/hero-slides': typeof BackendHeroSlidesRoute
  '/backend/homepage': typeof BackendHomepageRoute
  '/backend/homepage-sections': typeof BackendHomepageSectionsRoute
  '/backend/integrations': typeof BackendIntegrationsRoute
  '/backend/lifestyle-cards': typeof BackendLifestyleCardsRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/media': typeof BackendMediaRoute
  '/backend/nav-links': typeof BackendNavLinksRoute
  '/backend/newsletter': typeof BackendNewsletterRoute
  '/backend/orders': typeof BackendOrdersRouteWithChildren
  '/backend/pages': typeof BackendPagesRoute
  '/backend/products': typeof BackendProductsRoute
  '/backend/sales': typeof BackendSalesRoute
  '/backend/settings': typeof BackendSettingsRoute
  '/backend/site-settings': typeof BackendSiteSettingsRoute
  '/backend/submissions': typeof BackendSubmissionsRoute
  '/backend/users': typeof BackendUsersRoute
  '/backend/wms': typeof BackendWmsRoute
  '/brands/$handle': typeof BrandsHandleRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/backend/': typeof BackendIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/bundles/': typeof BundlesIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/backend/companies/$companyId': typeof BackendCompaniesCompanyIdRoute
  '/backend/companies/new': typeof BackendCompaniesNewRoute
  '/backend/customers/$customerId': typeof BackendCustomersCustomerIdRoute
  '/backend/customers/new': typeof BackendCustomersNewRoute
  '/backend/drafts/$draftId': typeof BackendDraftsDraftIdRoute
  '/backend/drafts/new': typeof BackendDraftsNewRoute
  '/backend/finance/invoices': typeof BackendFinanceInvoicesRouteWithChildren
  '/backend/finance/payments': typeof BackendFinancePaymentsRouteWithChildren
  '/backend/finance/receivables': typeof BackendFinanceReceivablesRoute
  '/backend/finance/reconciliation': typeof BackendFinanceReconciliationRoute
  '/backend/finance/refunds': typeof BackendFinanceRefundsRoute
  '/backend/finance/statements': typeof BackendFinanceStatementsRoute
  '/backend/orders/$orderId': typeof BackendOrdersOrderIdRoute
  '/backend/finance/invoices/$invoiceId': typeof BackendFinanceInvoicesInvoiceIdRoute
  '/backend/finance/payments/$paymentId': typeof BackendFinancePaymentsPaymentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/search': typeof SearchRoute
  '/trade': typeof TradeRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/company': typeof AccountCompanyRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/quotes': typeof AccountQuotesRoute
  '/admin/$': typeof AdminSplatRoute
  '/backend/catalog': typeof BackendCatalogRoute
  '/backend/categories': typeof BackendCategoriesRoute
  '/backend/checkout': typeof BackendCheckoutRoute
  '/backend/collections': typeof BackendCollectionsRoute
  '/backend/commerce': typeof BackendCommerceRoute
  '/backend/communications': typeof BackendCommunicationsRoute
  '/backend/companies': typeof BackendCompaniesRouteWithChildren
  '/backend/content': typeof BackendContentRoute
  '/backend/customers': typeof BackendCustomersRouteWithChildren
  '/backend/cutover': typeof BackendCutoverRoute
  '/backend/data-transfer': typeof BackendDataTransferRoute
  '/backend/drafts': typeof BackendDraftsRouteWithChildren
  '/backend/email-templates': typeof BackendEmailTemplatesRoute
  '/backend/feature-cards': typeof BackendFeatureCardsRoute
  '/backend/finance': typeof BackendFinanceRouteWithChildren
  '/backend/fulfilment': typeof BackendFulfilmentRoute
  '/backend/hero-slides': typeof BackendHeroSlidesRoute
  '/backend/homepage': typeof BackendHomepageRoute
  '/backend/homepage-sections': typeof BackendHomepageSectionsRoute
  '/backend/integrations': typeof BackendIntegrationsRoute
  '/backend/lifestyle-cards': typeof BackendLifestyleCardsRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/media': typeof BackendMediaRoute
  '/backend/nav-links': typeof BackendNavLinksRoute
  '/backend/newsletter': typeof BackendNewsletterRoute
  '/backend/orders': typeof BackendOrdersRouteWithChildren
  '/backend/pages': typeof BackendPagesRoute
  '/backend/products': typeof BackendProductsRoute
  '/backend/sales': typeof BackendSalesRoute
  '/backend/settings': typeof BackendSettingsRoute
  '/backend/site-settings': typeof BackendSiteSettingsRoute
  '/backend/submissions': typeof BackendSubmissionsRoute
  '/backend/users': typeof BackendUsersRoute
  '/backend/wms': typeof BackendWmsRoute
  '/brands/$handle': typeof BrandsHandleRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/backend': typeof BackendIndexRoute
  '/brands': typeof BrandsIndexRoute
  '/bundles': typeof BundlesIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/backend/companies/$companyId': typeof BackendCompaniesCompanyIdRoute
  '/backend/companies/new': typeof BackendCompaniesNewRoute
  '/backend/customers/$customerId': typeof BackendCustomersCustomerIdRoute
  '/backend/customers/new': typeof BackendCustomersNewRoute
  '/backend/drafts/$draftId': typeof BackendDraftsDraftIdRoute
  '/backend/drafts/new': typeof BackendDraftsNewRoute
  '/backend/finance/invoices': typeof BackendFinanceInvoicesRouteWithChildren
  '/backend/finance/payments': typeof BackendFinancePaymentsRouteWithChildren
  '/backend/finance/receivables': typeof BackendFinanceReceivablesRoute
  '/backend/finance/reconciliation': typeof BackendFinanceReconciliationRoute
  '/backend/finance/refunds': typeof BackendFinanceRefundsRoute
  '/backend/finance/statements': typeof BackendFinanceStatementsRoute
  '/backend/orders/$orderId': typeof BackendOrdersOrderIdRoute
  '/backend/finance/invoices/$invoiceId': typeof BackendFinanceInvoicesInvoiceIdRoute
  '/backend/finance/payments/$paymentId': typeof BackendFinancePaymentsPaymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/backend': typeof BackendRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/search': typeof SearchRoute
  '/trade': typeof TradeRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/company': typeof AccountCompanyRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/quotes': typeof AccountQuotesRoute
  '/admin/$': typeof AdminSplatRoute
  '/backend/catalog': typeof BackendCatalogRoute
  '/backend/categories': typeof BackendCategoriesRoute
  '/backend/checkout': typeof BackendCheckoutRoute
  '/backend/collections': typeof BackendCollectionsRoute
  '/backend/commerce': typeof BackendCommerceRoute
  '/backend/communications': typeof BackendCommunicationsRoute
  '/backend/companies': typeof BackendCompaniesRouteWithChildren
  '/backend/content': typeof BackendContentRoute
  '/backend/customers': typeof BackendCustomersRouteWithChildren
  '/backend/cutover': typeof BackendCutoverRoute
  '/backend/data-transfer': typeof BackendDataTransferRoute
  '/backend/drafts': typeof BackendDraftsRouteWithChildren
  '/backend/email-templates': typeof BackendEmailTemplatesRoute
  '/backend/feature-cards': typeof BackendFeatureCardsRoute
  '/backend/finance': typeof BackendFinanceRouteWithChildren
  '/backend/fulfilment': typeof BackendFulfilmentRoute
  '/backend/hero-slides': typeof BackendHeroSlidesRoute
  '/backend/homepage': typeof BackendHomepageRoute
  '/backend/homepage-sections': typeof BackendHomepageSectionsRoute
  '/backend/integrations': typeof BackendIntegrationsRoute
  '/backend/lifestyle-cards': typeof BackendLifestyleCardsRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/media': typeof BackendMediaRoute
  '/backend/nav-links': typeof BackendNavLinksRoute
  '/backend/newsletter': typeof BackendNewsletterRoute
  '/backend/orders': typeof BackendOrdersRouteWithChildren
  '/backend/pages': typeof BackendPagesRoute
  '/backend/products': typeof BackendProductsRoute
  '/backend/sales': typeof BackendSalesRoute
  '/backend/settings': typeof BackendSettingsRoute
  '/backend/site-settings': typeof BackendSiteSettingsRoute
  '/backend/submissions': typeof BackendSubmissionsRoute
  '/backend/users': typeof BackendUsersRoute
  '/backend/wms': typeof BackendWmsRoute
  '/brands/$handle': typeof BrandsHandleRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/backend/': typeof BackendIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/bundles/': typeof BundlesIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/backend/companies/$companyId': typeof BackendCompaniesCompanyIdRoute
  '/backend/companies/new': typeof BackendCompaniesNewRoute
  '/backend/customers/$customerId': typeof BackendCustomersCustomerIdRoute
  '/backend/customers/new': typeof BackendCustomersNewRoute
  '/backend/drafts/$draftId': typeof BackendDraftsDraftIdRoute
  '/backend/drafts/new': typeof BackendDraftsNewRoute
  '/backend/finance/invoices': typeof BackendFinanceInvoicesRouteWithChildren
  '/backend/finance/payments': typeof BackendFinancePaymentsRouteWithChildren
  '/backend/finance/receivables': typeof BackendFinanceReceivablesRoute
  '/backend/finance/reconciliation': typeof BackendFinanceReconciliationRoute
  '/backend/finance/refunds': typeof BackendFinanceRefundsRoute
  '/backend/finance/statements': typeof BackendFinanceStatementsRoute
  '/backend/orders/$orderId': typeof BackendOrdersOrderIdRoute
  '/backend/finance/invoices/$invoiceId': typeof BackendFinanceInvoicesInvoiceIdRoute
  '/backend/finance/payments/$paymentId': typeof BackendFinancePaymentsPaymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/backend'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/trade'
    | '/account/addresses'
    | '/account/company'
    | '/account/invoices'
    | '/account/quotes'
    | '/admin/$'
    | '/backend/catalog'
    | '/backend/categories'
    | '/backend/checkout'
    | '/backend/collections'
    | '/backend/commerce'
    | '/backend/communications'
    | '/backend/companies'
    | '/backend/content'
    | '/backend/customers'
    | '/backend/cutover'
    | '/backend/data-transfer'
    | '/backend/drafts'
    | '/backend/email-templates'
    | '/backend/feature-cards'
    | '/backend/finance'
    | '/backend/fulfilment'
    | '/backend/hero-slides'
    | '/backend/homepage'
    | '/backend/homepage-sections'
    | '/backend/integrations'
    | '/backend/lifestyle-cards'
    | '/backend/login'
    | '/backend/media'
    | '/backend/nav-links'
    | '/backend/newsletter'
    | '/backend/orders'
    | '/backend/pages'
    | '/backend/products'
    | '/backend/sales'
    | '/backend/settings'
    | '/backend/site-settings'
    | '/backend/submissions'
    | '/backend/users'
    | '/backend/wms'
    | '/brands/$handle'
    | '/bundle/$slug'
    | '/checkout/success'
    | '/collection/$slug'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/backend/'
    | '/brands/'
    | '/bundles/'
    | '/account/orders/$orderId'
    | '/backend/companies/$companyId'
    | '/backend/companies/new'
    | '/backend/customers/$customerId'
    | '/backend/customers/new'
    | '/backend/drafts/$draftId'
    | '/backend/drafts/new'
    | '/backend/finance/invoices'
    | '/backend/finance/payments'
    | '/backend/finance/receivables'
    | '/backend/finance/reconciliation'
    | '/backend/finance/refunds'
    | '/backend/finance/statements'
    | '/backend/orders/$orderId'
    | '/backend/finance/invoices/$invoiceId'
    | '/backend/finance/payments/$paymentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/trade'
    | '/account/addresses'
    | '/account/company'
    | '/account/invoices'
    | '/account/quotes'
    | '/admin/$'
    | '/backend/catalog'
    | '/backend/categories'
    | '/backend/checkout'
    | '/backend/collections'
    | '/backend/commerce'
    | '/backend/communications'
    | '/backend/companies'
    | '/backend/content'
    | '/backend/customers'
    | '/backend/cutover'
    | '/backend/data-transfer'
    | '/backend/drafts'
    | '/backend/email-templates'
    | '/backend/feature-cards'
    | '/backend/finance'
    | '/backend/fulfilment'
    | '/backend/hero-slides'
    | '/backend/homepage'
    | '/backend/homepage-sections'
    | '/backend/integrations'
    | '/backend/lifestyle-cards'
    | '/backend/login'
    | '/backend/media'
    | '/backend/nav-links'
    | '/backend/newsletter'
    | '/backend/orders'
    | '/backend/pages'
    | '/backend/products'
    | '/backend/sales'
    | '/backend/settings'
    | '/backend/site-settings'
    | '/backend/submissions'
    | '/backend/users'
    | '/backend/wms'
    | '/brands/$handle'
    | '/bundle/$slug'
    | '/checkout/success'
    | '/collection/$slug'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin'
    | '/backend'
    | '/brands'
    | '/bundles'
    | '/account/orders/$orderId'
    | '/backend/companies/$companyId'
    | '/backend/companies/new'
    | '/backend/customers/$customerId'
    | '/backend/customers/new'
    | '/backend/drafts/$draftId'
    | '/backend/drafts/new'
    | '/backend/finance/invoices'
    | '/backend/finance/payments'
    | '/backend/finance/receivables'
    | '/backend/finance/reconciliation'
    | '/backend/finance/refunds'
    | '/backend/finance/statements'
    | '/backend/orders/$orderId'
    | '/backend/finance/invoices/$invoiceId'
    | '/backend/finance/payments/$paymentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/backend'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/trade'
    | '/account/addresses'
    | '/account/company'
    | '/account/invoices'
    | '/account/quotes'
    | '/admin/$'
    | '/backend/catalog'
    | '/backend/categories'
    | '/backend/checkout'
    | '/backend/collections'
    | '/backend/commerce'
    | '/backend/communications'
    | '/backend/companies'
    | '/backend/content'
    | '/backend/customers'
    | '/backend/cutover'
    | '/backend/data-transfer'
    | '/backend/drafts'
    | '/backend/email-templates'
    | '/backend/feature-cards'
    | '/backend/finance'
    | '/backend/fulfilment'
    | '/backend/hero-slides'
    | '/backend/homepage'
    | '/backend/homepage-sections'
    | '/backend/integrations'
    | '/backend/lifestyle-cards'
    | '/backend/login'
    | '/backend/media'
    | '/backend/nav-links'
    | '/backend/newsletter'
    | '/backend/orders'
    | '/backend/pages'
    | '/backend/products'
    | '/backend/sales'
    | '/backend/settings'
    | '/backend/site-settings'
    | '/backend/submissions'
    | '/backend/users'
    | '/backend/wms'
    | '/brands/$handle'
    | '/bundle/$slug'
    | '/checkout/success'
    | '/collection/$slug'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/backend/'
    | '/brands/'
    | '/bundles/'
    | '/account/orders/$orderId'
    | '/backend/companies/$companyId'
    | '/backend/companies/new'
    | '/backend/customers/$customerId'
    | '/backend/customers/new'
    | '/backend/drafts/$draftId'
    | '/backend/drafts/new'
    | '/backend/finance/invoices'
    | '/backend/finance/payments'
    | '/backend/finance/receivables'
    | '/backend/finance/reconciliation'
    | '/backend/finance/refunds'
    | '/backend/finance/statements'
    | '/backend/orders/$orderId'
    | '/backend/finance/invoices/$invoiceId'
    | '/backend/finance/payments/$paymentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BackendRouteRoute: typeof BackendRouteRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  SearchRoute: typeof SearchRoute
  TradeRoute: typeof TradeRoute
  BrandsHandleRoute: typeof BrandsHandleRoute
  BundleSlugRoute: typeof BundleSlugRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  PagesSlugRoute: typeof PagesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  BundlesIndexRoute: typeof BundlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend': {
      id: '/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof BackendRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/': {
      id: '/bundles/'
      path: '/bundles'
      fullPath: '/bundles/'
      preLoaderRoute: typeof BundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/': {
      id: '/backend/'
      path: '/'
      fullPath: '/backend/'
      preLoaderRoute: typeof BackendIndexRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/bundle/$slug': {
      id: '/bundle/$slug'
      path: '/bundle/$slug'
      fullPath: '/bundle/$slug'
      preLoaderRoute: typeof BundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$handle': {
      id: '/brands/$handle'
      path: '/brands/$handle'
      fullPath: '/brands/$handle'
      preLoaderRoute: typeof BrandsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/wms': {
      id: '/backend/wms'
      path: '/wms'
      fullPath: '/backend/wms'
      preLoaderRoute: typeof BackendWmsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/users': {
      id: '/backend/users'
      path: '/users'
      fullPath: '/backend/users'
      preLoaderRoute: typeof BackendUsersRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/submissions': {
      id: '/backend/submissions'
      path: '/submissions'
      fullPath: '/backend/submissions'
      preLoaderRoute: typeof BackendSubmissionsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/site-settings': {
      id: '/backend/site-settings'
      path: '/site-settings'
      fullPath: '/backend/site-settings'
      preLoaderRoute: typeof BackendSiteSettingsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/settings': {
      id: '/backend/settings'
      path: '/settings'
      fullPath: '/backend/settings'
      preLoaderRoute: typeof BackendSettingsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/sales': {
      id: '/backend/sales'
      path: '/sales'
      fullPath: '/backend/sales'
      preLoaderRoute: typeof BackendSalesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/products': {
      id: '/backend/products'
      path: '/products'
      fullPath: '/backend/products'
      preLoaderRoute: typeof BackendProductsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/pages': {
      id: '/backend/pages'
      path: '/pages'
      fullPath: '/backend/pages'
      preLoaderRoute: typeof BackendPagesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/orders': {
      id: '/backend/orders'
      path: '/orders'
      fullPath: '/backend/orders'
      preLoaderRoute: typeof BackendOrdersRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/newsletter': {
      id: '/backend/newsletter'
      path: '/newsletter'
      fullPath: '/backend/newsletter'
      preLoaderRoute: typeof BackendNewsletterRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/nav-links': {
      id: '/backend/nav-links'
      path: '/nav-links'
      fullPath: '/backend/nav-links'
      preLoaderRoute: typeof BackendNavLinksRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/media': {
      id: '/backend/media'
      path: '/media'
      fullPath: '/backend/media'
      preLoaderRoute: typeof BackendMediaRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/login': {
      id: '/backend/login'
      path: '/login'
      fullPath: '/backend/login'
      preLoaderRoute: typeof BackendLoginRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/lifestyle-cards': {
      id: '/backend/lifestyle-cards'
      path: '/lifestyle-cards'
      fullPath: '/backend/lifestyle-cards'
      preLoaderRoute: typeof BackendLifestyleCardsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/integrations': {
      id: '/backend/integrations'
      path: '/integrations'
      fullPath: '/backend/integrations'
      preLoaderRoute: typeof BackendIntegrationsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/homepage-sections': {
      id: '/backend/homepage-sections'
      path: '/homepage-sections'
      fullPath: '/backend/homepage-sections'
      preLoaderRoute: typeof BackendHomepageSectionsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/homepage': {
      id: '/backend/homepage'
      path: '/homepage'
      fullPath: '/backend/homepage'
      preLoaderRoute: typeof BackendHomepageRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/hero-slides': {
      id: '/backend/hero-slides'
      path: '/hero-slides'
      fullPath: '/backend/hero-slides'
      preLoaderRoute: typeof BackendHeroSlidesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/fulfilment': {
      id: '/backend/fulfilment'
      path: '/fulfilment'
      fullPath: '/backend/fulfilment'
      preLoaderRoute: typeof BackendFulfilmentRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/finance': {
      id: '/backend/finance'
      path: '/finance'
      fullPath: '/backend/finance'
      preLoaderRoute: typeof BackendFinanceRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/feature-cards': {
      id: '/backend/feature-cards'
      path: '/feature-cards'
      fullPath: '/backend/feature-cards'
      preLoaderRoute: typeof BackendFeatureCardsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/email-templates': {
      id: '/backend/email-templates'
      path: '/email-templates'
      fullPath: '/backend/email-templates'
      preLoaderRoute: typeof BackendEmailTemplatesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/drafts': {
      id: '/backend/drafts'
      path: '/drafts'
      fullPath: '/backend/drafts'
      preLoaderRoute: typeof BackendDraftsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/data-transfer': {
      id: '/backend/data-transfer'
      path: '/data-transfer'
      fullPath: '/backend/data-transfer'
      preLoaderRoute: typeof BackendDataTransferRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/cutover': {
      id: '/backend/cutover'
      path: '/cutover'
      fullPath: '/backend/cutover'
      preLoaderRoute: typeof BackendCutoverRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/customers': {
      id: '/backend/customers'
      path: '/customers'
      fullPath: '/backend/customers'
      preLoaderRoute: typeof BackendCustomersRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/content': {
      id: '/backend/content'
      path: '/content'
      fullPath: '/backend/content'
      preLoaderRoute: typeof BackendContentRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/companies': {
      id: '/backend/companies'
      path: '/companies'
      fullPath: '/backend/companies'
      preLoaderRoute: typeof BackendCompaniesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/communications': {
      id: '/backend/communications'
      path: '/communications'
      fullPath: '/backend/communications'
      preLoaderRoute: typeof BackendCommunicationsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/commerce': {
      id: '/backend/commerce'
      path: '/commerce'
      fullPath: '/backend/commerce'
      preLoaderRoute: typeof BackendCommerceRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/collections': {
      id: '/backend/collections'
      path: '/collections'
      fullPath: '/backend/collections'
      preLoaderRoute: typeof BackendCollectionsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/checkout': {
      id: '/backend/checkout'
      path: '/checkout'
      fullPath: '/backend/checkout'
      preLoaderRoute: typeof BackendCheckoutRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/categories': {
      id: '/backend/categories'
      path: '/categories'
      fullPath: '/backend/categories'
      preLoaderRoute: typeof BackendCategoriesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/catalog': {
      id: '/backend/catalog'
      path: '/catalog'
      fullPath: '/backend/catalog'
      preLoaderRoute: typeof BackendCatalogRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/quotes': {
      id: '/account/quotes'
      path: '/quotes'
      fullPath: '/account/quotes'
      preLoaderRoute: typeof AccountQuotesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/invoices': {
      id: '/account/invoices'
      path: '/invoices'
      fullPath: '/account/invoices'
      preLoaderRoute: typeof AccountInvoicesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/company': {
      id: '/account/company'
      path: '/company'
      fullPath: '/account/company'
      preLoaderRoute: typeof AccountCompanyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/backend/orders/$orderId': {
      id: '/backend/orders/$orderId'
      path: '/$orderId'
      fullPath: '/backend/orders/$orderId'
      preLoaderRoute: typeof BackendOrdersOrderIdRouteImport
      parentRoute: typeof BackendOrdersRoute
    }
    '/backend/finance/statements': {
      id: '/backend/finance/statements'
      path: '/statements'
      fullPath: '/backend/finance/statements'
      preLoaderRoute: typeof BackendFinanceStatementsRouteImport
      parentRoute: typeof BackendFinanceRoute
    }
    '/backend/finance/refunds': {
      id: '/backend/finance/refunds'
      path: '/refunds'
      fullPath: '/backend/finance/refunds'
      preLoaderRoute: typeof BackendFinanceRefundsRouteImport
      parentRoute: typeof BackendFinanceRoute
    }
    '/backend/finance/reconciliation': {
      id: '/backend/finance/reconciliation'
      path: '/reconciliation'
      fullPath: '/backend/finance/reconciliation'
      preLoaderRoute: typeof BackendFinanceReconciliationRouteImport
      parentRoute: typeof BackendFinanceRoute
    }
    '/backend/finance/receivables': {
      id: '/backend/finance/receivables'
      path: '/receivables'
      fullPath: '/backend/finance/receivables'
      preLoaderRoute: typeof BackendFinanceReceivablesRouteImport
      parentRoute: typeof BackendFinanceRoute
    }
    '/backend/finance/payments': {
      id: '/backend/finance/payments'
      path: '/payments'
      fullPath: '/backend/finance/payments'
      preLoaderRoute: typeof BackendFinancePaymentsRouteImport
      parentRoute: typeof BackendFinanceRoute
    }
    '/backend/finance/invoices': {
      id: '/backend/finance/invoices'
      path: '/invoices'
      fullPath: '/backend/finance/invoices'
      preLoaderRoute: typeof BackendFinanceInvoicesRouteImport
      parentRoute: typeof BackendFinanceRoute
    }
    '/backend/drafts/new': {
      id: '/backend/drafts/new'
      path: '/new'
      fullPath: '/backend/drafts/new'
      preLoaderRoute: typeof BackendDraftsNewRouteImport
      parentRoute: typeof BackendDraftsRoute
    }
    '/backend/drafts/$draftId': {
      id: '/backend/drafts/$draftId'
      path: '/$draftId'
      fullPath: '/backend/drafts/$draftId'
      preLoaderRoute: typeof BackendDraftsDraftIdRouteImport
      parentRoute: typeof BackendDraftsRoute
    }
    '/backend/customers/new': {
      id: '/backend/customers/new'
      path: '/new'
      fullPath: '/backend/customers/new'
      preLoaderRoute: typeof BackendCustomersNewRouteImport
      parentRoute: typeof BackendCustomersRoute
    }
    '/backend/customers/$customerId': {
      id: '/backend/customers/$customerId'
      path: '/$customerId'
      fullPath: '/backend/customers/$customerId'
      preLoaderRoute: typeof BackendCustomersCustomerIdRouteImport
      parentRoute: typeof BackendCustomersRoute
    }
    '/backend/companies/new': {
      id: '/backend/companies/new'
      path: '/new'
      fullPath: '/backend/companies/new'
      preLoaderRoute: typeof BackendCompaniesNewRouteImport
      parentRoute: typeof BackendCompaniesRoute
    }
    '/backend/companies/$companyId': {
      id: '/backend/companies/$companyId'
      path: '/$companyId'
      fullPath: '/backend/companies/$companyId'
      preLoaderRoute: typeof BackendCompaniesCompanyIdRouteImport
      parentRoute: typeof BackendCompaniesRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/backend/finance/payments/$paymentId': {
      id: '/backend/finance/payments/$paymentId'
      path: '/$paymentId'
      fullPath: '/backend/finance/payments/$paymentId'
      preLoaderRoute: typeof BackendFinancePaymentsPaymentIdRouteImport
      parentRoute: typeof BackendFinancePaymentsRoute
    }
    '/backend/finance/invoices/$invoiceId': {
      id: '/backend/finance/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/backend/finance/invoices/$invoiceId'
      preLoaderRoute: typeof BackendFinanceInvoicesInvoiceIdRouteImport
      parentRoute: typeof BackendFinanceInvoicesRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BackendCompaniesRouteChildren {
  BackendCompaniesCompanyIdRoute: typeof BackendCompaniesCompanyIdRoute
  BackendCompaniesNewRoute: typeof BackendCompaniesNewRoute
}

const BackendCompaniesRouteChildren: BackendCompaniesRouteChildren = {
  BackendCompaniesCompanyIdRoute: BackendCompaniesCompanyIdRoute,
  BackendCompaniesNewRoute: BackendCompaniesNewRoute,
}

const BackendCompaniesRouteWithChildren =
  BackendCompaniesRoute._addFileChildren(BackendCompaniesRouteChildren)

interface BackendCustomersRouteChildren {
  BackendCustomersCustomerIdRoute: typeof BackendCustomersCustomerIdRoute
  BackendCustomersNewRoute: typeof BackendCustomersNewRoute
}

const BackendCustomersRouteChildren: BackendCustomersRouteChildren = {
  BackendCustomersCustomerIdRoute: BackendCustomersCustomerIdRoute,
  BackendCustomersNewRoute: BackendCustomersNewRoute,
}

const BackendCustomersRouteWithChildren =
  BackendCustomersRoute._addFileChildren(BackendCustomersRouteChildren)

interface BackendDraftsRouteChildren {
  BackendDraftsDraftIdRoute: typeof BackendDraftsDraftIdRoute
  BackendDraftsNewRoute: typeof BackendDraftsNewRoute
}

const BackendDraftsRouteChildren: BackendDraftsRouteChildren = {
  BackendDraftsDraftIdRoute: BackendDraftsDraftIdRoute,
  BackendDraftsNewRoute: BackendDraftsNewRoute,
}

const BackendDraftsRouteWithChildren = BackendDraftsRoute._addFileChildren(
  BackendDraftsRouteChildren,
)

interface BackendFinanceInvoicesRouteChildren {
  BackendFinanceInvoicesInvoiceIdRoute: typeof BackendFinanceInvoicesInvoiceIdRoute
}

const BackendFinanceInvoicesRouteChildren: BackendFinanceInvoicesRouteChildren =
  {
    BackendFinanceInvoicesInvoiceIdRoute: BackendFinanceInvoicesInvoiceIdRoute,
  }

const BackendFinanceInvoicesRouteWithChildren =
  BackendFinanceInvoicesRoute._addFileChildren(
    BackendFinanceInvoicesRouteChildren,
  )

interface BackendFinancePaymentsRouteChildren {
  BackendFinancePaymentsPaymentIdRoute: typeof BackendFinancePaymentsPaymentIdRoute
}

const BackendFinancePaymentsRouteChildren: BackendFinancePaymentsRouteChildren =
  {
    BackendFinancePaymentsPaymentIdRoute: BackendFinancePaymentsPaymentIdRoute,
  }

const BackendFinancePaymentsRouteWithChildren =
  BackendFinancePaymentsRoute._addFileChildren(
    BackendFinancePaymentsRouteChildren,
  )

interface BackendFinanceRouteChildren {
  BackendFinanceInvoicesRoute: typeof BackendFinanceInvoicesRouteWithChildren
  BackendFinancePaymentsRoute: typeof BackendFinancePaymentsRouteWithChildren
  BackendFinanceReceivablesRoute: typeof BackendFinanceReceivablesRoute
  BackendFinanceReconciliationRoute: typeof BackendFinanceReconciliationRoute
  BackendFinanceRefundsRoute: typeof BackendFinanceRefundsRoute
  BackendFinanceStatementsRoute: typeof BackendFinanceStatementsRoute
}

const BackendFinanceRouteChildren: BackendFinanceRouteChildren = {
  BackendFinanceInvoicesRoute: BackendFinanceInvoicesRouteWithChildren,
  BackendFinancePaymentsRoute: BackendFinancePaymentsRouteWithChildren,
  BackendFinanceReceivablesRoute: BackendFinanceReceivablesRoute,
  BackendFinanceReconciliationRoute: BackendFinanceReconciliationRoute,
  BackendFinanceRefundsRoute: BackendFinanceRefundsRoute,
  BackendFinanceStatementsRoute: BackendFinanceStatementsRoute,
}

const BackendFinanceRouteWithChildren = BackendFinanceRoute._addFileChildren(
  BackendFinanceRouteChildren,
)

interface BackendOrdersRouteChildren {
  BackendOrdersOrderIdRoute: typeof BackendOrdersOrderIdRoute
}

const BackendOrdersRouteChildren: BackendOrdersRouteChildren = {
  BackendOrdersOrderIdRoute: BackendOrdersOrderIdRoute,
}

const BackendOrdersRouteWithChildren = BackendOrdersRoute._addFileChildren(
  BackendOrdersRouteChildren,
)

interface BackendRouteRouteChildren {
  BackendCatalogRoute: typeof BackendCatalogRoute
  BackendCategoriesRoute: typeof BackendCategoriesRoute
  BackendCheckoutRoute: typeof BackendCheckoutRoute
  BackendCollectionsRoute: typeof BackendCollectionsRoute
  BackendCommerceRoute: typeof BackendCommerceRoute
  BackendCommunicationsRoute: typeof BackendCommunicationsRoute
  BackendCompaniesRoute: typeof BackendCompaniesRouteWithChildren
  BackendContentRoute: typeof BackendContentRoute
  BackendCustomersRoute: typeof BackendCustomersRouteWithChildren
  BackendCutoverRoute: typeof BackendCutoverRoute
  BackendDataTransferRoute: typeof BackendDataTransferRoute
  BackendDraftsRoute: typeof BackendDraftsRouteWithChildren
  BackendEmailTemplatesRoute: typeof BackendEmailTemplatesRoute
  BackendFeatureCardsRoute: typeof BackendFeatureCardsRoute
  BackendFinanceRoute: typeof BackendFinanceRouteWithChildren
  BackendFulfilmentRoute: typeof BackendFulfilmentRoute
  BackendHeroSlidesRoute: typeof BackendHeroSlidesRoute
  BackendHomepageRoute: typeof BackendHomepageRoute
  BackendHomepageSectionsRoute: typeof BackendHomepageSectionsRoute
  BackendIntegrationsRoute: typeof BackendIntegrationsRoute
  BackendLifestyleCardsRoute: typeof BackendLifestyleCardsRoute
  BackendLoginRoute: typeof BackendLoginRoute
  BackendMediaRoute: typeof BackendMediaRoute
  BackendNavLinksRoute: typeof BackendNavLinksRoute
  BackendNewsletterRoute: typeof BackendNewsletterRoute
  BackendOrdersRoute: typeof BackendOrdersRouteWithChildren
  BackendPagesRoute: typeof BackendPagesRoute
  BackendProductsRoute: typeof BackendProductsRoute
  BackendSalesRoute: typeof BackendSalesRoute
  BackendSettingsRoute: typeof BackendSettingsRoute
  BackendSiteSettingsRoute: typeof BackendSiteSettingsRoute
  BackendSubmissionsRoute: typeof BackendSubmissionsRoute
  BackendUsersRoute: typeof BackendUsersRoute
  BackendWmsRoute: typeof BackendWmsRoute
  BackendIndexRoute: typeof BackendIndexRoute
}

const BackendRouteRouteChildren: BackendRouteRouteChildren = {
  BackendCatalogRoute: BackendCatalogRoute,
  BackendCategoriesRoute: BackendCategoriesRoute,
  BackendCheckoutRoute: BackendCheckoutRoute,
  BackendCollectionsRoute: BackendCollectionsRoute,
  BackendCommerceRoute: BackendCommerceRoute,
  BackendCommunicationsRoute: BackendCommunicationsRoute,
  BackendCompaniesRoute: BackendCompaniesRouteWithChildren,
  BackendContentRoute: BackendContentRoute,
  BackendCustomersRoute: BackendCustomersRouteWithChildren,
  BackendCutoverRoute: BackendCutoverRoute,
  BackendDataTransferRoute: BackendDataTransferRoute,
  BackendDraftsRoute: BackendDraftsRouteWithChildren,
  BackendEmailTemplatesRoute: BackendEmailTemplatesRoute,
  BackendFeatureCardsRoute: BackendFeatureCardsRoute,
  BackendFinanceRoute: BackendFinanceRouteWithChildren,
  BackendFulfilmentRoute: BackendFulfilmentRoute,
  BackendHeroSlidesRoute: BackendHeroSlidesRoute,
  BackendHomepageRoute: BackendHomepageRoute,
  BackendHomepageSectionsRoute: BackendHomepageSectionsRoute,
  BackendIntegrationsRoute: BackendIntegrationsRoute,
  BackendLifestyleCardsRoute: BackendLifestyleCardsRoute,
  BackendLoginRoute: BackendLoginRoute,
  BackendMediaRoute: BackendMediaRoute,
  BackendNavLinksRoute: BackendNavLinksRoute,
  BackendNewsletterRoute: BackendNewsletterRoute,
  BackendOrdersRoute: BackendOrdersRouteWithChildren,
  BackendPagesRoute: BackendPagesRoute,
  BackendProductsRoute: BackendProductsRoute,
  BackendSalesRoute: BackendSalesRoute,
  BackendSettingsRoute: BackendSettingsRoute,
  BackendSiteSettingsRoute: BackendSiteSettingsRoute,
  BackendSubmissionsRoute: BackendSubmissionsRoute,
  BackendUsersRoute: BackendUsersRoute,
  BackendWmsRoute: BackendWmsRoute,
  BackendIndexRoute: BackendIndexRoute,
}

const BackendRouteRouteWithChildren = BackendRouteRoute._addFileChildren(
  BackendRouteRouteChildren,
)

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountCompanyRoute: typeof AccountCompanyRoute
  AccountInvoicesRoute: typeof AccountInvoicesRoute
  AccountQuotesRoute: typeof AccountQuotesRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountCompanyRoute: AccountCompanyRoute,
  AccountInvoicesRoute: AccountInvoicesRoute,
  AccountQuotesRoute: AccountQuotesRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BackendRouteRoute: BackendRouteRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  SearchRoute: SearchRoute,
  TradeRoute: TradeRoute,
  BrandsHandleRoute: BrandsHandleRoute,
  BundleSlugRoute: BundleSlugRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  PagesSlugRoute: PagesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  BundlesIndexRoute: BundlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
